name: CI

on: [push]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: pip install -r requirements.txt

      - name: Run linters
        run: inv lint --check

      - name: run tests
        run: inv test
